---

- name: Pre-tasks for all hosts
  hosts: all
  become: true
  pre_tasks:
    - name: DNF update cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false

- name: Install base
  become: true
  hosts: all
  roles:
    - base

- name: Install IPA server
  become: true
  hosts: ipaserver
  vars_files:
    - ipa-sensitive-data.yml
    - ipa-data.yml
  roles:
    - ipaserver

- name: Install IPA replica
  become: true
  hosts: ipareplica
  vars_files:
    - ipa-sensitive-data.yml
    - ipa-data.yml
  roles:
    - ipareplica

- name: Preconfigure IPA clients
  hosts: server:workstation:compute
  become: true
  tasks:
    - name: Remove /home mount location to prep for automount
      ansible.builtin.mount:
        path: /home
        state: absent
    - name: Add /fs mount point for NFS filesystems
      ansible.builtin.file:
        path: /fs
        state: directory
        owner: root
        group: root
        mode: "0755"

- name: Configure IPA clients
  hosts: server:workstation:compute
  become: true
  vars_files:
    - ipa-sensitive-data.yml
    - ipa-data.yml
  roles:
    - ipaclient

- name: Install server tools
  become: true
  hosts: server:workstation:compute
  roles:
    - server

- name: Install workstation tools
  become: true
  hosts: workstation:compute
  roles:
    - workstation

- name: Install GPU tools
  become: true
  hosts: compute
  roles:
    - nvidia
