---

- name: Pre-tasks for all hosts
  hosts: all
  become: true
  pre_tasks:
    - name: DNF update cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false

- name: Install base
  become: true
  hosts: all
  roles:
    - base

- name: Install IPA server
  become: true
  hosts: ipaserver
  vars_files:
    - ipa-sensitive-data.yml
    - ipa-data.yml
  roles:
    - ipaserver

- name: Install IPA replica
  become: true
  hosts: ipareplica
  vars_files:
    - ipa-sensitive-data.yml
    - ipa-data.yml
  roles:
    - ipareplica

- name: Configure IPA clients
  hosts: compute
  become: true
  vars_files:
    - ipa-sensitive-data.yml
    - ipa-data.yml
  roles:
    - ipaclient

- name: Install compute
  become: true
  hosts: compute
  roles:
    - ui
    - nvidia
