- name: Install slurm baseline
  become: true
  hosts: slurmworker:slurmcontroller:slurmlogin
  tasks:
    - name: Ensure slurm and munge are installed
      ansible.builtin.dnf:
        name:
        - munge
        - munge-libs
        - munge-devel
        - slurm
        - slurm-slurmd
        - slurm-devel
        - slurm-contribs
        - slurm-doc
    - name: Copy munge key to compute and controller hosts
      ansible.builtin.copy:
        src: etc/munge/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'
    - name: Ensure munge is enabled at boot
      ansible.builtin.systemd_service:
        name: munge
        enabled: true
        state: started
    - name: Add /etc/slurm directory
      ansible.builtin.file:
        path: /etc/slurm
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Allow slurm to write in /var/spool/slurm
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: slurm
        group: slurm
        mode: "0755"
      loop:
       - /var/spool/slurm
       - /var/spool/slurm/d
       - /var/spool/slurm/ctld
    - name: Copy slurm config to hosts
      ansible.builtin.copy:
        src: etc/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: root
        group: root
        mode: '0644'
      register: slurmconf
    - name: Copy gres config to hosts
      ansible.builtin.copy:
        src: etc/slurm/gres.conf
        dest: /etc/slurm/gres.conf
        owner: root
        group: root
        mode: '0644'
      register: gresconf
    - name: Copy cgroup config
      ansible.builtin.copy:
        src: etc/slurm/cgroup.conf
        dest: /etc/slurm/cgroup.conf
        owner: root
        group: root
        mode: '0644'
      register: cgroupconf

- name: Slurmlogin node configuration
  become: true
  hosts: slurmlogin
  tasks:
    - name: Ensure slurm is disabled at boot
      ansible.builtin.systemd_service:
        name: slurmd
        enabled: false
        state: stopped

- name: Ensure slurm control services are running
  become: true
  hosts: slurmcontroller
  tasks:
    - name: Ensure slurmctld is installed
      ansible.builtin.dnf:
        name: slurm-slurmctld
    - name: Ensure slurmctld is enabled at boot
      ansible.builtin.systemd_service:
        name: slurmctld
        enabled: true
        state: started
    - name: Permit traffic for slurmctld
      ansible.posix.firewalld:
        port: "6817/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled
    - name: Restart slurmctld
      ansible.builtin.systemd_service:
        name: slurmctld
        enabled: true
        state: restarted
      when: slurmconf.changed or gresconf.changed
    - name: Permit traffic for srun
      ansible.posix.firewalld:
        port: "50000-52000/tcp"
        zone: public
        permanent: true
        immediate: true
        state: disabled

- name: Ensure slurm database services are running
  become: true
  hosts: slurmcontroller
  vars_files:
  - slurm-sensitive-data.yml
  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name:
        - mariadb-server
        - python3-PyMySQL
        - policycoreutils-python-utils
        - slurm-slurmdbd
    # - name: Allow mysql to read libaio.so.1
    #   community.general.sefcontext:
    #     target: '/lib64(/.*)?'
    #     setype: mysqld_db_t
    #     state: present
    - name: Apply new SELinux file context to filesystem
      ansible.builtin.command: restorecon -irv /lib64
      changed_when: false
    - name: start mariadb
      ansible.builtin.systemd_service:
        name: mariadb
        state: started
        enabled: true
    - name: setup slurm db user
      mysql_user:
        name: "slurm"
        password: "{{ slurm_db_password }}"
        host: localhost
        login_unix_socket: /var/lib/mysql/mysql.sock
        priv: "*.*:USAGE/slurm_acct_db.*:ALL"
        state: present
    - name: configure slurmdbd.conf
      template:
        src: "slurmdbd.conf"
        dest: "/etc/slurm/slurmdbd.conf"
        owner: "slurm"
        mode: 0600
      notify:
      - restart slurmdbd
    - name: ensure slurmdbd is enabled
      ansible.builtin.systemd_service:
        name: slurmdbd
        enabled: true
        state: started
    - name: Permit traffic for slurmdbd
      ansible.posix.firewalld:
        port: "6819/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled
    - name: create cluster
      ansible.builtin.command: sacctmgr -i add cluster cluster0
      register: create_cluster_result
      failed_when: "create_cluster_result.rc != 0 and 'already exists' not in create_cluster_result.stdout"
      changed_when: "'already exists' not in create_cluster_result.stdout"
      run_once: true
  handlers:
      - name: restart slurmdbd
        ansible.builtin.systemd_service:
          name: slurmdbd
          state: restarted

- name: Ensure slurm worker services are running
  become: true
  hosts: slurmworker
  tasks:
    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
    - name: Create slurm directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      with_items:
        - /etc/slurm/shared
        - /etc/slurm/shared/bin
        - /etc/slurm/prolog.d
        - /etc/slurm/epilog.d
    - name: copy shared scripts
      template:
        src: "{{ item }}"
        dest: "/etc/slurm/shared/bin/"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
      - etc/slurm/shared/bin/*
    - name: copy prolog scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/slurm/prolog.d/"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
      - etc/slurm/prolog.d/*
    - name: copy epilog scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/slurm/epilog.d/"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
      - etc/slurm/epilog.d/*
    - name: copy prolog/epilog wrappers
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/slurm/"
        owner: root
        group: root
        mode: 0755
      loop:
      - etc/slurm/prolog.sh
      - etc/slurm/epilog.sh
    - name: Ensure slurmd is enabled at boot
      ansible.builtin.systemd_service:
        name: slurmd
        enabled: true
        state: started
    - name: Restart slurmd
      ansible.builtin.systemd_service:
        name: slurmd
        enabled: true
        state: restarted
      when: slurmconf.changed or gresconf.changed or cgroupconf.changed
    # - name: Permit traffic for slurmd
    #   ansible.posix.firewalld:
    #     port: "6818/tcp"
    #     zone: public
    #     permanent: true
    #     immediate: true
    #     state: enabled

- name: Install enroot
  hosts: slurmworker:slurmlogin
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name:
        - git
        - gcc
        - make
        - libcap
        - libtool
        - automake
        - libmd-devel
        - jq
        - squashfs-tools
        - parallel
        - fuse-overlayfs
        - pigz
        - squashfuse
        - rpmlint
    - name: Install enroot
      ansible.builtin.dnf:
        name:
        - https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot-3.5.0-1.el8.x86_64.rpm
        - https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot+caps-3.5.0-1.el8.x86_64.rpm
        disable_gpg_check: true
    - name: Copy enroot config
      ansible.builtin.copy:
        src: etc/enroot/enroot.conf
        dest: /etc/enroot/enroot.conf
        owner: root
        group: root
        mode: '0644'
    - name: check if kernel unpriv enabled
      ansible.builtin.shell: "cat /proc/cmdline | grep 'namespace.unpriv_enable=1'"
      register: kernel_unpriv_enable
      failed_when: kernel_unpriv_enable.rc == 127
      changed_when: kernel_unpriv_enable.rc == 1
    - name: check if user namespaces enabled
      ansible.builtin.shell: "cat /proc/cmdline | grep 'user_namespace.enable=1'"
      register: kernel_user_namespace
      failed_when: kernel_user_namespace.rc == 127
      changed_when: kernel_user_namespace.rc == 1
    - name: install grubby if needed
      ansible.builtin.dnf:
        name: "grubby"
        state: "present"
      when: ((kernel_unpriv_enable.rc == 1) or (kernel_user_namespace.rc == 1))
    - name: add kernel options to use enroot
      ansible.builtin.command: "grubby --update-kernel=ALL --args={{ item }}"
      when: ((kernel_unpriv_enable.rc == 1) or (kernel_user_namespace.rc == 1))
      with_items:
        - "namespace.unpriv_enable=1"
        - "user_namespace.enable=1"
      notify:
      - reboot node
  handlers:
      - name: reboot node
        ansible.builtin.reboot:
            msg: "Reboot initiated by Ansible after enroot installation"
    # # These are optional
    # - name: set max_user_namespaces
    #   sysctl:
    #     name: user.max_user_namespaces
    #     value: "{{ enroot_max_user_namespaces }}"
    #     state: present
    # - name: set max_mnt_namespaces
    #   sysctl:
    #     name: user.max_mnt_namespaces
    #     value: "{{ enroot_max_mnt_namespaces }}"
    #     state: present

- name: Install pyxis
  hosts: slurmworker
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name: util-linux
    - name: install slurm-pmi hook
      ansible.builtin.file:
        path: /etc/enroot/hooks.d/50-slurm-pmi.sh
        state: link
        src: /usr/share/enroot/hooks.d/50-slurm-pmi.sh
    - name: install slurm-pytorch hook
      ansible.builtin.file:
        path: /etc/enroot/hooks.d/50-slurm-pytorch.sh
        state: link
        src: /usr/share/enroot/hooks.d/50-slurm-pytorch.sh
    - name: create pyxis source dir
      ansible.builtin.file:
        path: /usr/local/src/pyxis
        state: directory
        mode: "0755"
    - name: copy pyxis source
      ansible.builtin.unarchive:
        src: "https://github.com/NVIDIA/pyxis/archive/refs/tags/v0.19.0.tar.gz"
        remote_src: yes
        dest: /usr/local/src/pyxis
        extra_opts:
          - --strip-components=1
    - name: clean pyxis source directory
      ansible.builtin.command:
        chdir: /usr/local/src/pyxis
        argv:
          - make
          - clean
      register: pyxis_make_clean
      failed_when: false
      changed_when: pyxis_make_clean.rc == 0
    - name: build pyxis
      ansible.builtin.command:
        chdir: /usr/local/src/pyxis
        argv:
          - make
          - -j
      environment:
        CPPFLAGS: "-I /usr/include/slurm"
      register: result
      changed_when: "result.stdout != \"make: Nothing to be done for 'all'.\""
      notify:
        - restart slurmd
    # Needed for 17.11, but not for 19.05. Doesn't hurt either way.
    - name: copy top-level plugstack file
      ansible.builtin.copy:
        src: etc/slurm/plugstack.conf
        dest: "/etc/slurm/"
        mode: "0644"
      notify:
        - restart slurmd
    - name: copy pyxis plugstack file
      ansible.builtin.copy:
        src: etc/slurm/plugstack.conf.d/pyxis.conf
        dest: "/etc/slurm/plugstack.conf.d/"
        mode: "0644"
      notify:
        - restart slurmd
    - name: set pyxis shared-object permissions
      ansible.builtin.file:
        path: "/usr/local/src/pyxis/spank_pyxis.so"
        mode: 0755
    # - name: resize /run partition
    #   mount:
    #     name: /run
    #     src: tmpfs
    #     opts: size=50%
    #     fstype: tmpfs
    #     state: mounted
  handlers:
      - name: restart slurmd
        ansible.builtin.systemd_service:
          name: slurmd
          state: restarted
