- name: Ensure base package groups are installed
  ansible.builtin.dnf:
    name:
      - "@Workstation"
      - "@Console Internet Tools"
      - "@Graphical Administration Tools"
      - "@Headless Management"
      - "@System Tools"
      - "@Development Tools"
      - "@RPM Development Tools"
      - "@Container Management"
      - "@Scientific Support"
      - "@VideoLAN Client"

- name: Ensure GUI tools are present
  ansible.builtin.dnf:
    name:
      - gnome-tweaks
      - gnome-extensions-app
      - file-roller
      - file-roller-nautilus
      - audacity
      - heif-pixbuf-loader
      - webp-pixbuf-loader
      - slurm-gui
