- name: Ensure epel is present
  ansible.builtin.dnf:
    name: epel-release

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Ensure base package groups are installed
  ansible.builtin.dnf:
    name:
      - "@Workstation"
      - "@Console Internet Tools"
      - "@Graphical Administration Tools"
      - "@Headless Management"
      - "@System Tools"
      - "@Development Tools"
      - "@RPM Development Tools"
      - "@Container Management"
      - "@Scientific Support"
      - "@VideoLAN Client"

- name: Ensure UI tools are present
  ansible.builtin.dnf:
    name:
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome
      - openconnect
      - gnome-tweaks
      - gnome-extensions-app

- name: Ensure CLI tools are present
  ansible.builtin.dnf:
    name:
      - htop
      - task-spooler
      - yt-dlp
      - vim
      - emacs
      - tcsh
      - pass
      - pass-otp
      - pwgen
      - cachefilesd
      - python3-ansible-lint

- name: Ensure development tools are present
  ansible.builtin.dnf:
    name:
      - munge
      - munge-devel
      - freeipmi
      - freeipmi-devel
      - lua
      - lua-devel
      - mariadb
      - mariadb-devel
      - man2html
      - numatop
      - numactl-devel
      - pam-devel
      - pmix-devel
      - readline-devel
      - http-parser
      - http-parser-devel
      - json-c
      - json-c-devel
      - libyaml
      - libyaml-devel
      - libjwt
      - libjwt-devel
      - cpp-jwt-devel
      - rrdtool
      - rrdtool-devel
      - libselinux-devel

- name: Make sure cachefilesd is running
  ansible.builtin.systemd_service:
    name: cachefilesd
    enabled: true
    state: started

- name: Install flathub
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
