- name: Ensure epel is present
  ansible.builtin.dnf:
    name: epel-release

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Ensure base package groups are installed
  ansible.builtin.dnf:
    name:
      - "@Workstation"
      - "@Console Internet Tools"
      - "@Graphical Administration Tools"
      - "@Headless Management"
      - "@System Tools"
      - "@Development Tools"
      - "@RPM Development Tools"
      - "@Container Management"
      - "@Scientific Support"
      - "@VideoLAN Client"

- name: Ensure VPN utilities are present
  ansible.builtin.dnf:
    name:
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome
      - openconnect

- name: Ensure utilities are present
  ansible.builtin.dnf:
    name:
      - htop
      - task-spooler
      - yt-dlp
      - vim
      - emacs
      - tcsh

- name: Ensure GUI utilities are present
  ansible.builtin.dnf:
    name:
      - gnome-tweaks
      - gnome-extensions-app

- name: Install flathub
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
