- name: Ensure NVIDIA CUDA repo is present
  ansible.builtin.yum_repository:
    name: "{{ nvidia_cuda_repo_name }}"
    description: "{{ nvidia_cuda_repo_description }}"
    baseurl: "{{ nvidia_driver_rhel_cuda_repo_baseurl }}"
    gpgkey: "{{ nvidia_driver_rhel_cuda_repo_gpgkey }}"

- name: "Reset NVIDIA driver stream"
  ansible.builtin.dnf:
    name:
      - nvidia-driver
      - "@nvidia-driver"
    state: absent
    autoremove: true
  when: nvidia_driver_reset_stream

- name: Ensure NVIDIA driver is present
  ansible.builtin.dnf:
    name: "{{ '@nvidia-driver:' + nvidia_driver_branch }}"

- name: Ensure CUDA is present
  ansible.builtin.dnf:
    name: "cuda-12-3"

- name: Ensure NVIDIA utilities are present
  ansible.builtin.dnf:
    name:
      - nvtop
      - datacenter-gpu-manager
      - libnvidia-container-tools

- name: Ensure NVIDIA DCGM service is running
  ansible.builtin.systemd_service:
    name: nvidia-dcgm
    enabled: true
    state: started
