- name: Ensure NVIDIA CUDA repo is present
  ansible.builtin.yum_repository:
    name: "{{ nvidia_cuda_repo_name }}"
    description: "{{ nvidia_cuda_repo_description }}"
    baseurl: "{{ nvidia_driver_rhel_cuda_repo_baseurl }}"
    gpgkey: "{{ nvidia_driver_rhel_cuda_repo_gpgkey }}"

- name: "Remove NVIDIA driver"
  ansible.builtin.command: dnf remove @nvidia-driver nvidia-driver kmod-nvidia-open-dkms libnvidia-cfg nvidia-modprobe -y
  become: true
  when: nvidia_driver_reset_stream

- name: "Remove NVIDIA module"
  ansible.builtin.command: dnf module reset nvidia-driver -y
  become: true
  when: nvidia_driver_reset_stream

- name: "Install NVIDIA driver"
  ansible.builtin.command: dnf module install "{{ 'nvidia-driver:' + nvidia_driver_branch }}" --allowerasing -y
  become: true
  when: nvidia_driver_reset_stream

# - name: "Remove NVIDIA driver"
#   ansible.builtin.dnf:
#     name: nvidia-driver
#     state: absent
#   when: nvidia_driver_reset_stream

- name: Ensure NVIDIA driver is present
  ansible.builtin.dnf:
    name: "{{ '@nvidia-driver:' + nvidia_driver_branch }}"

- name: Ensure CUDA is present
  ansible.builtin.dnf:
    name: "cuda-12-4"

- name: Ensure NVIDIA utilities are present
  ansible.builtin.dnf:
    name:
      - nvtop
      - datacenter-gpu-manager
      - libnvidia-container-tools

- name: Ensure NVIDIA DCGM service is running
  ansible.builtin.systemd_service:
    name: nvidia-dcgm
    enabled: true
    state: started
