#!/usr/bin/env bash
set -ex

command -v enroot >/dev/null || exit 0  # enroot not installed

runtime_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/run/enroot/$(id -u)"')"
mkdir -p "$runtime_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$runtime_path"
#chmod 0755 "$(dirname $runtime_path)"
chmod 0700 "$runtime_path"

cache_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/tmp/enroot-cache-$(id -u)"')"
mkdir -p "$cache_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$cache_path"
chmod 0700 "$cache_path"

data_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/tmp/enroot-data-$(id -u)"')"
mkdir -p "$data_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$data_path"
chmod 0700 "$data_path"
