- name: Ensure epel is present
  ansible.builtin.dnf:
    name: epel-release

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Ensure CLI tools are present
  ansible.builtin.dnf:
    name:
      - realmd
      - wget
      - nmap
      - bash-completion
      - htop
      - task-spooler
      - yt-dlp
      - vim
      - emacs
      - tcsh
      - pass
      - pass-otp
      - pwgen
      - cachefilesd
      - python3-ansible-lint
      - screen
      - tmux
      - cloud-utils-growpart
      - podman
      - podman-docker
      - podman-compose
      - podman-plugins
      - cockpit-podman
      - ansible-collection-containers-podman
      - redis
      - pcp-doc
      - pcp-gui
      - pcp-system-tools
      - pcp-pmda-podman
      - pcp-pmda-slurm
      - pcp-pmda-lmsensors
      - pcp-pmda-memcache
      - pcp-pmda-summary
      - pcp-pmda-systemd
      - podman-tui
      - unrar
      - the_silver_searcher
      - fd-find
      - ripgrep
      - mosh
      - iperf
      - p7zip

- name: Ensure development tools are present
  ansible.builtin.dnf:
    name:
      - automake
      - cmake
      - git
      - git-lfs
      - libmd-devel
      - libtool
      - rpm-build
      - freeipmi
      - freeipmi-devel
      - lua
      - lua-devel
      - mariadb
      - mariadb-server
      - mariadb-devel
      - man2html
      - numatop
      - numactl-devel
      - pam-devel
      - pmix-devel
      - readline-devel
      - http-parser
      - http-parser-devel
      - json-c
      - json-c-devel
      - jq
      - libyaml
      - libyaml-devel
      - libjwt
      - libjwt-devel
      - libtirpc
      - libwebp-tools
      - libwebp-devel
      - librsvg2-devel
      - libjpeg-turbo
      - libjpeg-turbo-utils
      - libjpeg-turbo-devel
      - libtree-sitter
      - libtree-sitter-devel
      - libpeas-devel
      - ninja-build
      - rrdtool
      - rrdtool-devel
      - libselinux-devel
      - openssl-devel
      - libXaw
      - libXaw-devel
      - Xaw3d
      - Xaw3d-devel
      - gtk3-devel
      - jansson
      - jansson-devel
      - sqlite
      - sqlite-libs
      - sqlite-devel
      - giflib
      - giflib-devel
      - ImageMagick
      - ImageMagick-devel
      - ImageMagick-libs
      - gnutls
      - gnutls-utils
      - gnutls-devel
      - systemd-devel
      - systemd-libs
      - perl-ExtUtils-MakeMaker
      - perl-DBI
      - perl-Switch
      - python3-mysqlclient
      - python3-pip
      - python3-virtualenv
      - python3-devel
      - pipx
      - python-unversioned-command
      - ctags
      - ShellCheck
      - texinfo
      - lz4
      - openldap-devel
      - openldap-compat
      - tk
      - tk-devel
      - curl
      - libcurl
      - libcurl-devel
