- name: Ensure epel is present
  ansible.builtin.dnf:
    name: epel-release

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Ensure CLI tools are present
  ansible.builtin.dnf:
    name:
      - realmd
      - wget
      - nmap
      - bash-completion
      - htop
      - task-spooler
      - yt-dlp
      - vim
      - emacs
      - tcsh
      - pass
      - pass-otp
      - pwgen
      - cachefilesd
      - python3-ansible-lint
      - screen
      - tmux
      - cloud-utils-growpart
      - podman
      - podman-docker
      - podman-compose
      - podman-plugins
      - cockpit-podman
      - ansible-collection-containers-podman
      - pcp-pmda-podman
      - podman-tui
      - unrar
      - the_silver_searcher

- name: Ensure development tools are present
  ansible.builtin.dnf:
    name:
      - automake
      - git
      - libmd-devel
      - libtool
      - rpm-build
      - munge
      - munge-libs
      - munge-devel
      - freeipmi
      - freeipmi-devel
      - lua
      - lua-devel
      - mariadb
      - mariadb-server
      - mariadb-devel
      - man2html
      - numatop
      - numactl-devel
      - pam-devel
      - pmix-devel
      - readline-devel
      - http-parser
      - http-parser-devel
      - json-c
      - json-c-devel
      - jq
      - libyaml
      - libyaml-devel
      - libjwt
      - libjwt-devel
      - cpp-jwt-devel
      - rrdtool
      - rrdtool-devel
      - libselinux-devel
      - openssl-devel
      - perl-ExtUtils-MakeMaker
      - perl-DBI
      - perl-Switch
      - python3-mysqlclient
      - python3-pip
      - python3-virtualenv
      - ctags

- name: Ensure cachefilesd is enabled and running
  ansible.builtin.systemd_service:
    name: cachefilesd
    enabled: true
    state: started
