- name: Ensure epel is present
  ansible.builtin.dnf:
    name: epel-release

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Ensure CLI tools are present
  ansible.builtin.dnf:
    name:
      - bash-completion
      - htop
      - task-spooler
      - yt-dlp
      - vim
      - emacs
      - tcsh
      - pass
      - pass-otp
      - pwgen
      - cachefilesd
      - python3-ansible-lint

- name: Ensure development tools are present
  ansible.builtin.dnf:
    name:
      - rpm-build
      - munge
      - munge-libs
      - munge-devel
      - freeipmi
      - freeipmi-devel
      - lua
      - lua-devel
      - mariadb
      - mariadb-devel
      - man2html
      - numatop
      - numactl-devel
      - pam-devel
      - pmix-devel
      - readline-devel
      - http-parser
      - http-parser-devel
      - json-c
      - json-c-devel
      - libyaml
      - libyaml-devel
      - libjwt
      - libjwt-devel
      - cpp-jwt-devel
      - rrdtool
      - rrdtool-devel
      - libselinux-devel
      - perl-ExtUtils-MakeMaker
      - openssl-devel 
      - perl-DBI
      - perl-Switch

- name: Ensure cachefilesd is enabled and running
  ansible.builtin.systemd_service:
    name: cachefilesd
    enabled: true
    state: started
