- name: Ensure cockpit and related modules are installed
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-pcp

- name: Ensure cockpit is enabled at boot
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true
