- name: Ensure Samba server tools are present
  ansible.builtin.dnf:
    name:
      - cockpit-file-sharing
      - ipa-client-samba

- name: Permit traffic for Samba
  ansible.posix.firewalld:
    service: samba-client
    permanent: true
    state: enabled

- name: Ensure smb is enabled at boot
  ansible.builtin.systemd_service:
    name: smb
    state: started
    enabled: true

- name: Ensure winbind is enabled at boot
  ansible.builtin.systemd_service:
    name: winbind
    state: started
    enabled: true