---

- name: Pre-tasks for all hosts
  hosts: all
  become: true
  pre_tasks:
    - name: DNF update cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false

- name: Install base
  become: true
  hosts: base
  roles:
    - base

- name: Install compute
  become: true
  hosts: compute
  roles:
    - compute
